# Creates the traefik IngressRoutes that allow for external access to the
# triton service. Two routes are created, one for gRPC and one for HTTP.
# Requires deployment of the traefik IngressRoute CRD, along with various roles
# and permissions, most easily accomplished through the referenced traefik
# helm chart. Will only be installed if the loadBalancing tag is set to true.

{{- if .Values.tags.loadBalancing }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ template "riva-server-ingressroute-http.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "riva-server.name" . }}
    chart: {{ template "riva-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  entryPoints:
    - tritonhttp
  routes:
    - match: PathPrefix(`/`)
      kind: Rule
      services:
        - name: {{ template "riva-server.fullname" . }}
          port: 8000
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ template "riva-server-ingressroute-grpc.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - tritongrpc
  routes:
    - match: PathPrefix(`/`)
      kind: Rule
      services:
        - name: {{ template "riva-server.fullname" . }}
          port: 8001
          scheme: h2c
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ template "riva-server-ingressroute-riva.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - tritonriva
  routes:
    - match: PathPrefix(`/`)
      kind: Rule
      services:
        - name: {{ template "riva-server.fullname" . }}
          port: 50051
          scheme: h2c
{{- end -}}