apiVersion: v1
kind: Secret
data:
  key: {{ .Values.modelRepoGenerator.modelDeployKey |  quote }}
metadata:
  creationTimestamp: null
  name: riva-model-deploy-key
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ template "riva-server.fullname" . }}
    chart: {{ template "riva-server.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    type: {{ template "riva-server.fullname" . }}
---
apiVersion: v1
data:
  .dockerconfigjson: {{ template "ngcPullSecret" . }}
kind: Secret
metadata:
  creationTimestamp: null
  name: imagepullsecret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ template "riva-server.fullname" . }}
    chart: {{ template "riva-server.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    type: {{ template "riva-server.fullname" . }}
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
data:
  apikey: {{ .Values.ngcCredentials.password | quote }}
metadata:
  creationTimestamp: null
  name: modelpullsecret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ template "riva-server.fullname" . }}
    chart: {{ template "riva-server.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    type: {{ template "riva-server.fullname" . }}
