apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "riva-server-metrics-monitor.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ template "riva-server.fullname" . }}
    chart: {{ template "riva-server.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    type: {{ template "riva-server.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "riva-server-metrics.name" . }}
  endpoints:
  - port: metrics
    interval: 15s