apiVersion: v1
kind: Service
metadata:
  name: {{ template "riva-server.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ template "riva-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ template "riva-server.fullname" . }}
spec:
  type: NodePort
  ports:
    - port: 8015
      targetPort: assistant
      nodePort: {{ .Values.assistant.nodePort }}
      name: assistant
    - port: 9000
      targetPort: peer
      nodePort: {{ add .Values.assistant.nodePort 1 }}
      name: peer
    - port: 8081
      targetPort: redis-commander
      nodePort: {{ add .Values.assistant.nodePort 2 }}
      name: redis-commander
  selector:
    app.kubernetes.io/instance: {{ template "riva-server.fullname" . }}
    release: {{ .Release.Name }}
    type: {{ template "riva-server.fullname" . }}-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "riva-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ template "riva-server.fullname" . }}
    chart: {{ template "riva-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ template "riva-server.fullname" . }}
spec:
  clusterIP: None
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: triton-http
    - port: 8001
      targetPort: grpc
      protocol: TCP
      name: triton-grpc
    - port: 8002
      targetPort: metrics
      protocol: TCP
      name: triton-metrics
    - port: 50051
      targetPort: riva-grpc
      protocol: TCP
      name: riva-speech
  selector:
    app.kubernetes.io/instance: {{ template "riva-server.fullname" . }}
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "riva-server-metrics.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "riva-server-metrics.name" . }}
    chart: {{ template "riva-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ template "riva-server.fullname" . }}
  annotations:
    alpha.monitoring.coreos.com/non-namespaced: "true"
spec:
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
    protocol: TCP
  selector:
    app.kubernetes.io/instance: {{ template "riva-server.fullname" . }}
    release: {{ .Release.Name }}