{
 "title": "Triton Inference Server",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Active Triton Instances",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(nv_inference_count) by (instance))"
    }
   ]
  },
  {
   "title": "Proportion of Requests by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(nv_inference_count[1m])) / ignoring(pod) group_left sum (rate(nv_inference_count[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Cumulative Inference Requests by Pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(nv_inference_request_success) by (pod)",
     "legendFormat": "Success {{pod}}"
    },
    {
     "expr": "sum(nv_inference_request_failure) by (pod)",
     "legendFormat": "Failure {{pod}}"
    }
   ]
  },
  {
   "title": "Compute Time by Model (milliseconds)",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(nv_inference_compute_infer_duration_us[30s])) by (model) / 1000",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Average Queue Time by Pod (microseconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg(rate(nv_inference_queue_duration_us[30s])/(1+rate(nv_inference_request_success[30s]))) by (pod)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}